apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-drainer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-drainer-role
subjects:
- kind: ServiceAccount
  name: node-drainer-sa
  namespace: default

