apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-drainer-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes"]
  verbs: ["get", "list"]

