apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-drainer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-drainer
  template:
    metadata:
      labels:
        app: node-drainer
    spec:
      serviceAccountName: node-drainer-sa
      containers:
      - name: node-drainer
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CHECK_INTERVAL
            value: "{{ .Values.settings.checkInterval }}"
          - name: THRESHOLD_USAGE
            value: "{{ .Values.settings.thresholdUsage }}"
          - name: THRESHOLD_TIME
            value: "{{ .Values.settings.thresholdTime }}"
          - name: DRY_RUN
            value: "{{ .Values.settings.dryRun }}"
          - name: NODE_LABEL_SELECTOR
            value: "{{ .Values.settings.nodeLabelSelector }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

