name: Publish Helm Chart

on:
  push:
    branches:
      - main  # Change this to your desired branch if necessary
    paths:
      - 'chart/**'  # Trigger the workflow when changes are made in the 'chart/' directory

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0  # Use the appropriate version of Helm

      - name: Authenticate with GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Package Helm Chart
        run: helm package chart --destination packaged

      - name: Push Helm Chart to GitHub Container Registry
        run: |
          helm push packaged/$(yq e '.name' chart/Chart.yaml)-$(yq e '.version' chart/Chart.yaml).tgz oci://ghcr.io/${{ github.repository_owner }}/charts
